const fakeData = [
    {id: 0, name: 'Forest a shelter animal.', img: 'https://i.imgur.com/zI1XRbK.png'},
    {id: 1, name: 'Babysit during PTA meetings.', img: 'https://i.imgur.com/6u1IQUr.png'},
    {id: 2, name: 'Building birdhouses for your neighbors.', img: 'https://i.imgur.com/UK25lkV.png'},
    {id: 3, name: 'Child Support', img: 'https://i.imgur.com/Atocc0W.png'},
    {id: 4, name: 'Clean water for children', img: 'https://i.imgur.com/ql25m8g.png'},
    {id: 5, name: 'Clean up your local park.', img: 'https://i.imgur.com/pvdbIKm.png'},
    {id: 6, name: 'Host a clothing swap.', img: 'https://i.imgur.com/oAa3bdk.png'},
    {id: 7, name: 'Give a seminar on driving safety.', img:'https://i.imgur.com/Ig8MP6h.png'},
    {id: 8, name: 'Food Charity', img: 'https://i.imgur.com/0QYwkuX.png'},
    {id: 9, name: 'Good education ', img: 'https://i.imgur.com/xo4nrWi.png'},
    {id: 10, name: 'Give IT help to local adults', img: 'https://i.imgur.com/xOtGuXa.png'},
    {id: 11, name: 'Organize books at the library.', img: 'https://i.imgur.com/EsIJ4KW.png'},
    {id: 12, name: 'Give free music lessons.', img: 'https://i.imgur.com/2zpH65g.png'},
    {id: 13, name: 'New books for children ', img: 'https://i.imgur.com/tcVxGIh.png'},
    {id: 14, name: 'Refuge shelter', img: 'https://i.imgur.com/5GdmGg5.png'},
    {id: 15, name: 'Host a river clean-up', img: 'https://i.imgur.com/quWsluS.png'},
    {id: 16, name: 'Collect school supplies.', img: 'https://i.imgur.com/Ow0iwvD.png'},
    {id: 17, name: 'Host a study group.', img: 'https://i.imgur.com/Hmb41Ek.png'},
    {id: 18, name: 'Collect stuffed animals.', img: 'https://i.imgur.com/ujf1uO0.png'},
    {id: 19, name: 'Teach people how to register to vote.', img: 'https://i.imgur.com/A8JKDgL.png'}];
    export default fakeData;